apiVersion: batch/v1
kind: CronJob
metadata:
  name: pi-app
spec:
  schedule: "*/10 * * * *"
  successfulJobsHistoryLimit: 20
  failedJobsHistoryLimit: 3
  startingDeadlineSeconds: 10
  jobTemplate:
    spec:
      backoffLimit: 2
      template:
        spec:
          restartPolicy: Never
          containers:
          - name: pi-app
            image: pi-app:latest
            imagePullPolicy: IfNotPresent
            env:
            - name: REDIS_HOST
              value: redis-0.redis
            resources:
              requests:
                cpu: 200m
                memory: 200Mi
              limits:
                cpu: 400m
                memory: 400Mi
