apiVersion: v1
kind: Namespace
metadata:
  name: staging
  labels:
    pod-security.kubernetes.io/enforce: restricted
    # pod-security.kubernetes.io/enforce-version: v1.34
    pod-security.kubernetes.io/enforce-version: "latest"

