apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: developer
  namespace: development
rules:
  - apiGroups:
      - ""
    resources:
      - events
      - pods
      - pods/log
      - pods/portforward
      - services
      - secrets
      - configmaps
      - persistentvolumeclaims
    verbs: ["*"]
  - apiGroups:
      - apps
      - autoscaling
      - batch
      - networking.k8s.io
      - policy
    resources: ["*"]
    verbs: ["*"]

