apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: storageclass-ephemeral
provisioner: k8s.io/minikube-hostpath
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
