apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
spec:
  serviceName: redis
  replicas: 3
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      terminationGracePeriodSeconds: 10
      initContainers:
        - name: redis-init
          image: redis:8.2.2
          command:
            - bash
            - "-c"
            - |
              set -ex
              # Generate server-id from Pod ordinal index.
              [[ `hostname` =~ -([0-9]+)$ ]] || exit 1
              ordinal=${BASH_REMATCH[1]}
              echo "ordinal ${ordinal}"
              # Copy appropriate config files from config-map to emptyDir.
              mkdir -p /redis/conf/
              if [[ $ordinal -eq 0 ]]; then
                cp /mnt/redis-role-config/primary.conf /redis/conf/redis.conf
              else
                cp /mnt/redis-role-config/replica.conf /redis/conf/redis.conf
              fi
              cat /redis/conf/redis.conf
          volumeMounts:
            - name: redis-role-config
              mountPath: /mnt/redis-role-config/
            - name: redis-config
              mountPath: /redis/conf/
      containers:
        - name: redis
          image: redis:8.2.2
          command: ["redis-server"]
          args: ["/redis/conf/redis.conf"]
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: redis-config
              mountPath: /redis/conf/
            - name: redis-data
              mountPath: /redis/data/
          resources:
            requests:
              cpu: 1
              memory: 1Gi
      volumes:
        - name: redis-role-config
          configMap:
            name: redis-role-config
        - name: redis-config
          emptyDir: {}
  volumeClaimTemplates:
    - metadata:
        name: redis-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
