apiVersion: v1
kind: Pod
metadata:
  name: k8s-app
  labels:
    app: k8s-app
spec:
  containers:
    - name: k8s-app
      image: k8s-app:latest
      imagePullPolicy: Never
      ports:
      - containerPort: 9090
      volumeMounts:
        - name: ephemeral
          mountPath: /ephemeral
  volumes:
    - name: ephemeral
      ephemeral:
        volumeClaimTemplate:
          metadata:
            labels:
              type: ephemeral
          spec:
            accessModes: ["ReadWriteOnce"]
            storageClassName: "storageclass-ephemeral"
            resources:
              requests:
                storage: 1Gi
